INSERT INTO users (name, age) VALUES ("Bob", 20);
INSERT INTO users (name, age) VALUES ("Jane", 22);
INSERT INTO users (name, age) VALUES ("Billie", 40);
INSERT INTO users (name, age) VALUES ("Harley", 28);
INSERT INTO users (name, age) VALUES ("Sue", 18);
INSERT INTO users (name, age) VALUES ("Mark", 32);
INSERT INTO users (name, age) VALUES ("Cameron", 37);
INSERT INTO users (name, age) VALUES ("Rhea", 38);
INSERT INTO users (name, age) VALUES ("Katie", 33);
INSERT INTO users (name, age) VALUES ("Tom", 35);
INSERT INTO users (name, age) VALUES ("Lisa", 19);
INSERT INTO users (name, age) VALUES ("Lala", 26);
INSERT INTO users (name, age) VALUES ("Bambi", 28);
INSERT INTO users (name, age) VALUES ("Jax", 24);
INSERT INTO users (name, age) VALUES ("Ellen", 50);
INSERT INTO users (name, age) VALUES ("Ariana", 56);
INSERT INTO users (name, age) VALUES ("Dorit", 54);
INSERT INTO users (name, age) VALUES ("Rinna", 58);
INSERT INTO users (name, age) VALUES ("Porsha", 52);
INSERT INTO users (name, age) VALUES ("Kandi", 20);


INSERT INTO projects (title, category, funding_goal, start_date,end_date) VALUES ("My Great Restaurant", "food", 1000, 2019-05-13,2019-08-23);
INSERT INTO projects (title, category, funding_goal, start_date,end_date) VALUES ("Movietown", "film", 123500, 2019-10-10,2019-12-31);
INSERT INTO projects (title, category, funding_goal, start_date,end_date) VALUES ("Safe Straws for the Planet", "consumer goods", 345800, 2019-01-13,2019-08-01);
INSERT INTO projects (title, category, funding_goal, start_date,end_date) VALUES ("Green Masheen", "food", 7800, 2019-04-11,2019-07-23);
INSERT INTO projects (title, category, funding_goal, start_date,end_date) VALUES ("Bags Bags Bags", "consumer goods", 12679, 2019-03-01,2019-06-23);
INSERT INTO projects (title, category, funding_goal, start_date,end_date) VALUES ("Comeback, Kid", "consumer goods", 4567, 2019-02-17,2019-05-30);
INSERT INTO projects (title, category, funding_goal, start_date,end_date) VALUES ("The Next Great Thing", "tech", 6789890, 2019-01-22,2019-09-19);
INSERT INTO projects (title, category, funding_goal, start_date,end_date) VALUES ("Snapgram", "tech", 469103, 2019-03-08,2019-11-29);
INSERT INTO projects (title, category, funding_goal, start_date,end_date) VALUES ("Make Good Choices", "film", 6780, 2019-04-01,2019-08-18);
INSERT INTO projects (title, category, funding_goal, start_date,end_date) VALUES ("The Red Carpet Red Carpet", "film", 1209, 2019-02-24,2019-09-22);

INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 20, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (250, 20, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (67, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2455, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (27, 5, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (280, 5, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (234, 4, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (533, 4, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (57, 20, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 19, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 18, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 17, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (548, 16, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 15, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (8, 14, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (780, 13, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (97, 13, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 13, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 7, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4, 6, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (277, 12, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 13, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 11, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 11, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 9, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 8, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 9, 2);