INSERT INTO users VALUES (1, 'a', 1);;
INSERT INTO users VALUES (2, 'aa', 12);
INSERT INTO users VALUES (3, 'as', 13);
INSERT INTO users VALUES (4, 'af', 14);
INSERT INTO users VALUES (5, 'ag', 15);
INSERT INTO users VALUES (6, 'ah', 16);
INSERT INTO users VALUES (7, 'aj', 17);
INSERT INTO users VALUES (8, 'ak', 18);
INSERT INTO users VALUES (9, 'al', 19);
INSERT INTO users VALUES (10, 'aq', 2);
INSERT INTO users VALUES (11, 'aw', 11);
INSERT INTO users VALUES (12, 'ar', 21);
INSERT INTO users VALUES (13, 'ae', 31);
INSERT INTO users VALUES (14, 'at', 41);
INSERT INTO users VALUES (15, 'ay', 51);
INSERT INTO users VALUES (16, 'au', 61);
INSERT INTO users VALUES (17, 'ai', 71);
INSERT INTO users VALUES (18, 'ao', 81);
INSERT INTO users VALUES (19, 'ab', 91);
INSERT INTO users VALUES (20, 'ap', 10);


INSERT INTO projects VALUES (12, "a", "a", "a", "a", "a");
INSERT INTO projects VALUES (13, "a", "a", "a", "a", "a");
INSERT INTO projects VALUES (14, "a", "a", "a", "a", "a");
INSERT INTO projects VALUES (15, "a", "a", "a", "a", "a");
INSERT INTO projects VALUES (16, "a", "a", "a", "a", "a");
INSERT INTO projects VALUES (17, "a", "a", "a", "a", "a");
INSERT INTO projects VALUES (18, "a", "a", "a", "a", "a");
INSERT INTO projects VALUES (19, "a", "a", "a", "a", "a");
INSERT INTO projects VALUES (11, "a", "a", "a", "a", "a");
INSERT INTO projects VALUES (21, "a", "a", "a", "a", "a");


INSERT INTO pledges VALUES (1,2,3,4);
INSERT INTO pledges VALUES (12,2,3,4);
INSERT INTO pledges VALUES (13,2,3,4);
INSERT INTO pledges VALUES (14,2,3,4);
INSERT INTO pledges VALUES (15,2,3,4);
INSERT INTO pledges VALUES (16,2,3,4);
INSERT INTO pledges VALUES (17,2,3,4);
INSERT INTO pledges VALUES (18,2,3,4);
INSERT INTO pledges VALUES (19,2,3,4);
INSERT INTO pledges VALUES (122,2,3,4);
INSERT INTO pledges VALUES (132,2,3,4);
INSERT INTO pledges VALUES (21,3,3,4);
INSERT INTO pledges VALUES (31,2,3,4);
INSERT INTO pledges VALUES (41,2,3,4);
INSERT INTO pledges VALUES (51,2,3,4);
INSERT INTO pledges VALUES (61,2,3,4);
INSERT INTO pledges VALUES (71,2,3,4);
INSERT INTO pledges VALUES (81,2,3,4);
INSERT INTO pledges VALUES (91,2,3,4);
INSERT INTO pledges VALUES (111,2,3,4);
INSERT INTO pledges VALUES (221,2,3,4);
INSERT INTO pledges VALUES (331,2,3,4);
INSERT INTO pledges VALUES (144,2,3,4);
INSERT INTO pledges VALUES (152,4,3,4);
INSERT INTO pledges VALUES (146,2,3,4);
INSERT INTO pledges VALUES (155,2,3,4);
INSERT INTO pledges VALUES (321,2,3,4);
INSERT INTO pledges VALUES (3561,2,3,4);
INSERT INTO pledges VALUES (231,2,3,4);
INSERT INTO pledges VALUES (2431,2,3,4);
